//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouHouReminder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TouHouReminder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Days&quot;: [
        ///    {
        ///      &quot;Time&quot;: &quot;January 5th&quot;,
        ///      &quot;Character&quot;: &quot;Yumemi Okazaki&quot;,
        ///      &quot;Name&quot;: &quot;The Professor&apos;s Day&quot;
        ///    },
        ///    {
        ///      &quot;Time&quot;: &quot;January 6th&quot;,
        ///      &quot;Character&quot;: &quot;Hakurei Reimu&quot;,
        ///      &quot;Name&quot;: &quot;Hakurei Reimu&apos;s Day&quot;
        ///    },
        ///    {
        ///      &quot;Time&quot;: &quot;January 7th&quot;,
        ///      &quot;Character&quot;: &quot;Kagiyama Hina&quot;,
        ///      &quot;Name&quot;: &quot;Kagiyama Hina&apos;s Day&quot;
        ///    },
        ///    {
        ///      &quot;Time&quot;: &quot;January 8th&quot;,
        ///      &quot;Character&quot;: &quot;Ibaraki Kasen&quot;,
        ///      &quot;Name&quot;: &quot;Ibaraki Kasen&apos;s Day&quot;
        ///    },
        ///    {
        ///      &quot;Time&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReservedString {
            get {
                return ResourceManager.GetString("ReservedString", resourceCulture);
            }
        }
    }
}
